apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ template "project.namespacedname" . }}-serving-cert'
  name: estauthorizedclients.cert-estuary.atelierhsn.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: '{{ .Release.Namespace }}'
          name: '{{ template "project.fullname" . }}-webhook-service'
          path: /convert
      conversionReviewVersions:
        - v1
