apiVersion: cert-estuary.atelierhsn.com/v1
kind: ESTAuthorizedClient
metadata:
  labels:
    app.kubernetes.io/name: cert-estuary
    app.kubernetes.io/managed-by: kustomize
  name: estauthorizedclient-sample
  namespace: cert-estuary-system
spec:
  subject: curl-est
  subjectAltNames:
    - curl-est.default.svc.cluster.local
    - curl-est.default.svc
  signerName: issuers.cert-manager.io/cert-estuary-system.cert-estuary-cert-estuary-issuer
  csrAutoApprove: false
