{{- if .Values.controller.enableWebhook}}
resources:
  - ../../../webhook

namespace: '{{ .Release.Namespace }}'

namePrefix: '{{ template "project.name" . }}-'

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: '{{ include "project.name" . }}'

patches:
  - path: webhookcainjection_patch.yaml

transformers:
  - label-transformer.yaml
{{- end }}
