image:
  # image.repository -- image repository to use.
  repository: ghcr.io/hsn723/cert-estuary
  # image.tag -- image tag to use.
  # @default -- `{{ .Chart.AppVersion }}`
  tag: v0.1.0
  # image.pullPolicy -- image pullPolicy.
  pullPolicy:  # Always

controller:
  # controller.replicas -- Specify the number of replicas of the controller Pod.
  replicas: 2

  # controller.resources -- Specify resources.
  resources:
    requests:
      cpu: 500m
      memory: 100Mi

  # controller.terminationGracePeriodSeconds -- Specify terminationGracePeriodSeconds.
  terminationGracePeriodSeconds: 10

  # controller.extraArgs -- Optional additional arguments.
  extraArgs: ["--leader-elect"]

  # issuerName -- Specify the name of the issuer.
  issuerName: selfsigned-issuer

  # enableWebhook -- Enable the webhook server. The webhook server is not yet implemented.
  enableWebhook: false
