apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: est-cert
  namespace: cert-estuary-system
  labels:
    app.kubernetes.io/name: cert-estuary
    app.kubernetes.io/managed-by: kustomize
spec:
  secretName: est-server-cert
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: cert-estuary-issuer
    kind: Issuer
  commonName: cert-estuary-est-server
  dnsNames:
    - cert-estuary-est-server.cert-estuary-system.svc.cluster.local
    - cert-estuary-est-server.cert-estuary-system.svc
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: ECDSA
    size: 256
