apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-estuary-issuer
  namespace: cert-estuary-system
  labels:
    app.kubernetes.io/name: cert-estuary
    app.kubernetes.io/managed-by: kustomize
spec:
  selfSigned: {}
