apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "project.name" . }}-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ template "project.name" . }}-est-service.{{ .Release.Namespace }}.svc
    - {{ template "project.name" . }}-est-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    {{- if .Values.controller.issuerName }}
    name: {{ .Values.controller.issuerName }}
    {{- else }}
    name: {{ template "project.name" . }}-selfsigned-issuer
    {{- end }}
  secretName: est-server-cert
