apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "project.name" . }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "project.chart" . }}'
  name: '{{ template "project.name" . }}-est-service'
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: est-server
  selector:
    app.kubernetes.io/name: '{{ include "project.name" . }}'
    app.kubernetes.io/component: controller
