name: Release Helm chart
on:
  push:
    branches:
      - master
    paths:
      - 'charts/cert-estuary/Chart.yaml'
permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/helm-release.yml@v1.0.14
    secrets: inherit
    with:
      upload_as_oci: true
      chart_name: cert-estuary
